### ISSUE TITLE
AirPlay2 setup resets the seekToTime

### ISSUE THREAD

**Issue by nandikaw** [brightcove/brightcove-player-sdk-ios-ssai#1]
After following the Airplay2 setup [AirPlay setup](https://docs.brightcove.com/ios-sdk/index.html#AirPlay), player encountered some issues.

Issue: When user disconnects the Chromecast session and handover to the local player, most of the time the video starts from the beginning even the correct seek time is provided to below method. (and the finished = NO)

`- (void)seekToTime:(CMTime)time toleranceBefore:(CMTime)toleranceBefore toleranceAfter:(CMTime)toleranceAfter completionHandler:(void (^_Nullable)(BOOL finished))completionHandler;`

If i configure the AVAudioSession as below, it seems to be working fine, but would like to use the latest configs.
`  [AVAudioSession.sharedInstance setCategory:AVAudioSessionCategoryPlayback error:nil];`

**Comment by timothyrodgers** [comment]
Brightcove does not provide technical support through GitHub. Please visit the Brightcove support portal at https://supportportal.brightcove.com/s/login/, or contact your account manager. AirPlay and Chromecast are unrelated. AVAudioSession settings do not affect seeking.
